# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(-2, 'Banned'), (-1, 'Expired'), (0, 'Draft'), (1, 'Sale'), (2, 'Booked'), (3, 'Sold')], default=0, verbose_name='Status')),
                ('date_of_sale', models.DateField(auto_now=True, verbose_name='Date of Sale')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.Seller')),
            ],
        ),
    ]
