# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171230_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.CharField(blank=True, max_length=255, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_quality',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Used')], default=1, verbose_name='Quality'),
        ),
    ]
