# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171117_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='product_status',
        ),
    ]
