# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 11:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180208_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_sale',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 18, 51, 40, 243257), verbose_name='Date of Sale'),
        ),
    ]
