# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20180213_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_sale',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 13, 11, 47, 28, 297776, tzinfo=utc), verbose_name='Date of Sale'),
        ),
    ]
