# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180213_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_sale',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Sale'),
        ),
    ]
