# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180213_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promote',
            field=models.BooleanField(default=False, verbose_name='Currently Promoted'),
        ),
    ]
