# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 12:27
from __future__ import unicode_literals

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_promote'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exp_date_promotion',
            field=models.DateTimeField(default=apps.products.models.one_day_hence, verbose_name='Expire Date'),
        ),
    ]
