# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_exp_date_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exp_date_promotion',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Expire Date'),
        ),
    ]
