# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0004_auto_20180208_1554'),
        ('offers', '0002_auto_20180212_2124'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=set([('buyer', 'product')]),
        ),
    ]
