# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20171117_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Decline'), (0, 'Pending'), (1, 'Accept'), (2, 'Rejected'), (3, 'Revoked')], default=0, verbose_name='Status'),
        ),
    ]
