# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Draft')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_track',
            field=models.CharField(blank=True, max_length=13, verbose_name='Tracking'),
        ),
    ]
