# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20180228_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_track',
            field=models.CharField(default='-รอการอัพเดท-', max_length=13, verbose_name='Tracking'),
        ),
    ]
