# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180228_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Wait'), (2, 'Receive'), (3, 'Success')], default=0, verbose_name='Status'),
        ),
    ]
