# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180306_1744'),
        ('orders', '0006_auto_20180222_2205'),
    ]

    operations = [
    ]
