# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_merge_20180306_1859'),
        ('orders', '0009_merge_20180306_1858'),
    ]

    operations = [
    ]
