# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_merge_20180306_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Receive'), (2, 'Success')], default=0, verbose_name='Status'),
        ),
    ]
