# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_bankaccount_security_number'),
        ('orders', '0012_order_payment_slip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.BankAccount'),
        ),
    ]
