# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_selected_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to='payment_slips'),
        ),
    ]
