# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='coin',
            field=models.IntegerField(default=0, verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='account',
            name='product_active_period',
            field=models.IntegerField(default=3, verbose_name='Expire Date'),
        ),
    ]
