# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171214_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telephone'),
        ),
    ]
