# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('category_type', models.IntegerField(choices=[(0, 'Normal'), (1, 'Promotion'), (2, 'Group'), (3, 'Tags')], default=0, verbose_name='Type')),
            ],
        ),
    ]
