# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20171117_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='categories.Category'),
            preserve_default=False,
        ),
    ]
