# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(blank=True, max_length=225, verbose_name='Address'),
        ),
    ]
