# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_seller_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
