# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sale_price',
            field=models.IntegerField(default=0),
        ),
    ]
