# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('object_trans', models.CharField(max_length=100)),
                ('date_action', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
            ],
        ),
    ]
