# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('values', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='properties',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='properties.Property'),
            preserve_default=False,
        ),
    ]
