# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_value_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='properties_string',
            field=models.CharField(max_length=100, verbose_name='Batch Code'),
        ),
    ]
