# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating'),
        ),
    ]
