# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_number'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', related_query_name='order_items', to='orders.OrderItem'),
            preserve_default=False,
        ),
    ]
