# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180304_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(choices=[(-1, 'Others'), (0, 'BBL'), (1, 'Kbank'), (2, 'Scb'), (3, 'Ktb'), (4, 'Tmb'), (5, 'Krungsri'), (6, 'Tanachart'), (7, 'Uob'), (8, 'Tisco'), (9, 'Lh'), (10, 'Cimb'), (11, 'Gsb')], default=-1)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('promptpay_phone_number', models.CharField(blank=True, max_length=20)),
                ('promptpay_citizen_id', models.CharField(blank=True, max_length=20)),
                ('card_type', models.IntegerField(choices=[(0, 'Visa'), (1, 'Mastercard')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
    ]
