# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_bankaccount_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='security_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
